{
 "title": "Arista General Statistics by IP",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "deviceType", "label": "Dispositivi", "query": "arista" },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(up{job=\"$deviceType\"},instance)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "label_values(intfCounter{job=\"$deviceType\", instance=~\"$device\"},intf)"
   }
  ]
 },
 "panels": [
  { "title": "Aggregated traffic by device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregated traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(intfCounter{job=\"$deviceType\",instance=\"$device\"}[1m])*8) without (intf)",
     "legendFormat": "{{type}} bytes {{direction}}"
    },
    {
     "expr": "sum(rate(intfPktCounter{job=\"$deviceType\",instance=\"$device\"}[1m])) without (intf)",
     "legendFormat": "{{type}} packets {{direction}}"
    }
   ]
  },
  { "title": "Traffic by interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "packets/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(intfPktCounter{job=\"$deviceType\",instance=\"$device\"}[1m])) without (type)",
     "legendFormat": "{{intf}} {{direction}}"
    }
   ]
  },
  {
   "title": "bits/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(intfCounter{job=\"$deviceType\",instance=\"$device\"}[1m])*8) without (type)",
     "legendFormat": "{{intf}} {{direction}}"
    }
   ]
  },
  { "title": "CPU & Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "fanSpeed{job=\"$deviceType\",instance=\"$device\"}",
     "legendFormat": "{{fan}}"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$deviceType\",instance=\"$device\"}[1m])",
     "legendFormat": "CPU Seconds"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "tempSensor{job=\"$deviceType\",instance=\"$device\",type=\"temperature\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Input/Output power levels",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "powerSensor{job=\"$deviceType\",instance=\"$device\"}",
     "legendFormat": "{{sensor}} {{direction}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "voltageSensor{job=\"$deviceType\",instance=\"$device\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic $interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(intfCounter{job=\"$deviceType\",instance=\"$device\",intf=\"$interface\",type=\"Octets\"}[1m])*8",
       "legendFormat": "{{type}} {{direction}}"
      },
      {
       "expr": "rate(intfPktCounter{job=\"$deviceType\",instance=\"$device\",intf=\"$interface\"}[1m])",
       "legendFormat": "{{type}} {{direction}}"
      }
     ]
    }
   ]
  }
 ]
}